### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by DanForder** [Benyamin428/snake-game#1]
## Site Output

- Your snake game is looking really clean and simple, this is a well-executed project and you’ve managed to fit a good amount of functionality in the time frame given
- I think you have the game nailed down, so if you were to continue with it I’d like to see some more work put into the UI of the project, maybe a splash of colour and page heading!

## Responsiveness

- Built mobile-first and looks great on mobile. Having the arrow key buttons is a great addition!

## Readability

- You have split your logic into functions really well on this project, which makes this code really easy to follow and understand
- Remember to use `const` when declaring a function (line 26, 40, e.g.), JavaScript will normally be pretty forgiving and work anyway, but you can’t guarantee it!
- There is quite a bit of repeated code with your “move” functions, perhaps these could be refactored into one function and use *parameters* to differentiate between directions?
- In your `spawnTailAfterFood` function, I’d recommend using a **guard clause** instead of wrapping everything in an `if` statement. Instead of “if the condition is all good, carry on”, you reverse the logic “if something is wrong, return immediately”. This can reduce indentation/ complexity, especially if we had multiple conditions. See code snippet for implementation:

```jsx
// your code
if(condition){
  // carry on with function logic
}

// guard clause
if(!condition) return;
// carry on with function logic
```

## Code Knowledge and Use

- Your use of `setTimeout` to re-call the movement function is awesome! Keeps the code really clean
- You’ve shown a great understanding of DOM-related JavaScript and I’m happy with where you’re at technically

**Comment by Benyamin428** [comment]
Thanks for the feedback Dan. I have updated my code to reflect the improvement suggestions.

- [x] Used const for all my functions
- [x] Refactored my move functions to one function
- [x] Used a guard clause for my spawnTailAfterFood function
